config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  root 'produtos#index'
  post 'produtos/create'
  patch 'produtos/:id' => 'produtos#update'

end

app/models/produtos.rb
class Produtos < ActiveRecord::Base
  validates :nome,  presence: true, length: { minimum: 3, maximum: 50 }
  validates :descricao,  presence: true, length: { maximum: 500 }
  validates :valor,  presence: true, numericality: true
  validates :quantidade,  presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def index
    @produtos = Produtos.all
  end
  def show
    @produto = Produtos.find(params[:id])
  end
  def new
  @produto = Produtos.new
  end
  def edit
    @produto = Produtos.find(params[:id])
  end
  def create
    @produto = Produtos.new(produto_params)
    if (@produto.save)
      flash[:success] = "Inserido com sucesso!"
      redirect_to @produto
    else
      flash[:error] = "Ocorreu um problema ao inserir!"
      render 'new'
    end
  end
  def update
    @produto = Produtos.find(params[:id])
    if (@produto.update_attributes(produto_params))
      flash[:success] = "Editado com sucesso!"
      redirect_to @produto
    else
      flash[:error] = "Ocorreu um problema ao editar!"
      render 'edit'
    end
  end
  def destroy
    @produto = Produtos.find(params[:id])
    if (@produto.destroy)
      flash[:success] = "Excluido com sucesso!"
    else
      flash[:error] = "Erro ao excluir!"
    end
    redirect_to :action => 'index'
  end
  
  private

    def produto_params
      params.permit(:nome, :descricao, :valor, :quantidade)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estoque Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
<div class="container">
  <nav class="navbar navbar-default" style="margin-top:20px">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/produtos">
        Estoque Rails
        </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Lista", root_path() %></li>
        <li><%= link_to "Novo", new_produto_path() %></li>
      </ul>
    </div>
  </nav>

<%= yield %>

</div>

</body>
</html>

app/views/produtos/edit.html.erb
<% if @produto.errors.any? %>
  <div class="alert alert-danger">
    <h3><%= pluralize(@produto.errors.count, "erro") %> ocorreram ao editar produto:</h3>
    <ul>
    <% @produto.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger">
    <em><%= flash[:error] %></em>
  </div>
<% end %>


<h1>Editar produto</h1>
<form action="/produtos/<%= @produto.id %>" method="post">
  <input name="_method" type="hidden" value="patch" />
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="form-group">
    <label>Nome</label>
    <input name="nome" class="form-control" value="<%= @produto.nome %>">
  </div>
  <div class="form-group">
    <label>Descricao</label>
    <input name="descricao" class="form-control" value="<%= @produto.descricao %>">
  </div>
  <div class="form-group">
    <label>Valor</label>
    <input name="valor" class="form-control" value="<%= @produto.valor %>">
  </div>
  <div class="form-group">
    <label>Quantidade</label>
    <input name="quantidade" type="number" class="form-control" value="<%= @produto.quantidade %>">
  </div>
  <button type="submit" class="btn
  btn-primary btn-block">Submit</button>
</form>

app/views/produtos/index.html.erb
<h1>Lista de produtos</h1>
<% if @produtos.any? %>
<table class="table table-striped table-bordered table-hover">
  <tbody>
    <% @produtos.each do |produto| %>
    <tr class="">
      <td><%= produto.nome %></td>
      <td><%= produto.valor %></td>
      <td><%= produto.descricao %></td>
      <td><%= produto.quantidade %></td>
      
      <td>
        <%= link_to (produto_path(produto)) do %>
          <span class="glyphicon glyphicon-search"></span>
        <% end %>
      </td>
      <td>
        <%= link_to (edit_produto_path(produto)) do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
      </td>
      <td>
        <%= link_to("Excluir", produto, method: :delete, data: { confirm: "Tem certeza que deseja excluir?" }) %>
          <span class="glyphicon glyphicon-trash"></span>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>Nenhum produto. Adicione o primeiro.</p>
<% end %>

app/views/produtos/new.html.erb
<% if @produto.errors.any? %>
  <div class="alert alert-danger">
    <h3><%= pluralize(@produto.errors.count, "erro") %> ocorreram ao criar produto:</h3>
    <ul>
    <% @produto.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger">
    <em><%= flash[:error] %></em>
  </div>
<% end %>

<h1>Novo produto</h1>
<form action="/produtos/create" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="form-group">
    <label>Nome</label>
    <input name="nome" class="form-control" value="">
  </div>
  <div class="form-group">
    <label>Descricao</label>
    <input name="descricao" class="form-control" value="">
  </div>
  <div class="form-group">
    <label>Valor</label>
    <input name="valor" class="form-control" value="">
  </div>
  <div class="form-group">
    <label>Quantidade</label>
    <input name="quantidade" type="number" class="form-control" value="">
  </div>
  <button type="submit" class="btn
  btn-primary btn-block">Submit</button>
</form>

app/views/produtos/show.html.erb
<% if flash[:success] %>
  <div class="alert alert-success">
    <em><%= flash[:success] %></em>
  </div>
<% end %>

<h1>Detalhes do produto: <%= @produto.nome %> </h1>
<ul>
  <li>
    <b>Valor:</b> R$ <%= @produto.valor %>
  </li>
  <li>
    <b>Descrição:</b> <%= @produto.descricao %>
  </li>
  <li>
    <b>Quantidade em estoque:</b> <%= @produto.quantidade %>
  </li>
</ul>